name: Release Dawn

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    uses: ./.github/workflows/build-dawn-windows.yml

  release:
    runs-on: lin-build
    needs: build-windows
    steps:
      - name: Checkout ngixi-builds repo
        uses: actions/checkout@v4
        with:
          clean: true

      - uses: ./.github/actions/setup-build
        with:
          build-dir: dawn-build

      - name: Download Dawn artifacts
        uses: actions/download-artifact@v4
        with:
          name: dawn-windows-assets

      - name: List downloaded files
        shell: bash
        run: |
          pwd
          ls -la
          find . -name "*.tar.gz"

      - name: Create release structure
        shell: bash
        run: |
          rm -rf dawn-release
          mkdir -p dawn-release/windows-x64
          tar -xzf dawn-win-msvc.tar.gz -C dawn-release/windows-x64

      - name: Create build.zig.zon
        shell: pwsh
        run: |
          $tag = "${{ vars.DAWN_TAG }}"
          # Parse tag, e.g., if "v20251026.130842", version = "2025.10.26"
          if ($tag -match "v(\d{4})(\d{2})(\d{2})\.\d+") {
            $version = "$($matches[1]).$($matches[2]).$($matches[3])"
          } else {
            Write-Error "Unrecognized DAWN_TAG format: $tag"
            exit 1
          }
          $content = ".{`n    .name = `"dawn`",`n    .version = `"$version`",`n    .paths = .{`"`"},`n}"
          Set-Content -Path "dawn-release/build.zig.zon" -Value $content -Force

      - name: Create release tar
        shell: bash
        run: |
          TAG="${{ vars.DAWN_TAG }}"
          cd dawn-release && tar -czf "../dawn-$TAG.tar.gz" *

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: dawn-release
          path: dawn-*.tar.gz

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dawn-${{ vars.DAWN_TAG }}
          name: Dawn ${{ vars.DAWN_TAG }}
          files: dawn-${{ vars.DAWN_TAG }}.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}