name: Build Dawn

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: WIN-BUILD
    
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    steps:
      - name: Checkout Dawn
        run: |
          if (-not (Test-Path dawn)) {
            git clone https://dawn.googlesource.com/dawn
          }
          cd dawn

      - name: Fetch dependencies
        run: |
          cd dawn
          python tools/fetch_dawn_dependencies.py

      - name: Configure CMake
        run: |
          cd dawn
          cmake -S . -B out/Release -DDAWN_FETCH_DEPENDENCIES=ON -DDAWN_ENABLE_INSTALL=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -GNinja

      - name: Build Dawn
        run: |
          cd dawn
          cmake --build out/Release

      - name: Install Dawn
        run: |
          cd dawn
          cmake --install out/Release --prefix install/Release
