name: Build Dawn Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Dawn - Windows x64
    permissions:
      contents: write
    uses: ./.github/workflows/buildDawnWindowsRelease.yml
