name: Build Dawn Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  setup:
    runs-on: WIN-BUILD
    steps:
      - name: Checkout ngixi-builds repo
        uses: actions/checkout@v4
        with:
          clean: false

      - uses: ./.github/actions/setup-build
        with:
          build-dir: dawn-build

  build-windows:
    runs-on: WIN-BUILD
    needs: setup
    defaults:
      run:
        working-directory: dawn-build
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    steps:

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Checkout Dawn
        shell: pwsh
        run: |
          if (-not (Test-Path dawn)) {
            git clone ${{ vars.DAWN_REPO }} dawn
          }

      - name: Checkout tag
        shell: pwsh
        run: |
          cd dawn
          git fetch --tags --force --quiet
          git checkout --quiet ${{ vars.DAWN_TAG }}
          git rev-parse --short HEAD | Out-File -Encoding ascii ..\DAWN_GIT.txt

      - name: Fetch deps
        shell: pwsh
        run: |
          cd dawn
          Copy-Item scripts/standalone.gclient .gclient -Force
          gclient sync

      - name: Configure (dawn shared dll)
        shell: cmd
        run: |
          cd dawn
          cmake -S . -B out -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_C_COMPILER=cl ^
            -DCMAKE_CXX_COMPILER=cl ^
            -DCMAKE_CXX_FLAGS="/DNOMINMAX /DWIN32_LEAN_AND_MEAN" ^
            -DCMAKE_SYSTEM_VERSION=10.0 ^
            -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL ^
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON ^
            -DCMAKE_C_FLAGS_RELEASE="/O2 /GL /Gw /Gy /Oi /DNDEBUG" ^
            -DCMAKE_CXX_FLAGS_RELEASE="/O2 /GL /Gw /Gy /Oi /MP /DNDEBUG" ^
            -DCMAKE_SHARED_LINKER_FLAGS_RELEASE="/INCREMENTAL:NO /OPT:REF /OPT:ICF /LTCG" ^
            -DCMAKE_EXE_LINKER_FLAGS_RELEASE="/INCREMENTAL:NO /OPT:REF /OPT:ICF /LTCG" ^
            -DBUILD_SHARED_LIBS=OFF ^
            -DDAWN_BUILD_MONOLITHIC_LIBRARY=SHARED ^
            -DDAWN_ENABLE_INSTALL=ON ^
            -DDAWN_BUILD_TESTS=OFF ^
            -DDAWN_BUILD_SAMPLES=OFF ^
            -DDAWN_BUILD_BENCHMARKS=OFF ^
            -DDAWN_ENABLE_BACKEND_D3D12=ON ^
            -DDAWN_ENABLE_BACKEND_VULKAN=ON ^
            -DDAWN_ENABLE_BACKEND_OPENGL=OFF ^
            -DDAWN_ENABLE_BACKEND_METAL=OFF ^
            -DDAWN_ENABLE_BACKEND_NULL=OFF ^
            -DTINT_BUILD_TESTS=OFF ^
            -DTINT_BUILD_SAMPLES=OFF ^
            -DTINT_BUILD_DOCS=OFF ^
            -DTINT_ENABLE_DXC=ON ^
            -DTINT_ENABLE_WGSL_READER=ON ^
            -DTINT_ENABLE_SPV_READER=OFF

      - name: Build (monolithic SHARED)
        shell: cmd
        run: |
          cd dawn
          cmake --build out --parallel

      - name: Install (monolithic SHARED)
        shell: cmd
        run: |
          cd dawn
          cmake --install out --prefix install

      - name: Create build.zig.zon
        shell: pwsh
        run: |
          $tag = "${{ vars.DAWN_TAG }}"
          # Parse tag, e.g., if "v20251026.130842", version = "2025.10.26"
          if ($tag -match "v(\d{4})(\d{2})(\d{2})\.\d+") {
            $version = "$($matches[1]).$($matches[2]).$($matches[3])"
          } else {
            Write-Error "Unrecognized DAWN_TAG format: $tag"
            exit 1
          }
          $content = ".{" + "`n" + "    .name = .dawn-win-msvc," + "`n" + "    .version = `"$version`"," + "`n" + "}"
          Set-Content -Path "dawn/install/build.zig.zon" -Value $content -Force

      - name: Create tar archive
        shell: cmd
        run: |
          cd dawn\install
          if exist ..\..\dawn-win-msvc.tar del ..\..\dawn-win-msvc.tar
          tar -cf ..\..\dawn-win-msvc.tar *

      - name: Report DLL dependents
        shell: cmd
        run: |
          cd dawn\install\bin
          if exist webgpu_dawn.dll dumpbin /dependents webgpu_dawn.dll > "DEPENDENTS.txt"

      - name: Upload Dawn artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dawn-windows-assets
          path: |
            dawn-build/dawn-win-msvc.tar
            dawn-build/DAWN_GIT.txt
