name: Build Wasmtime Windows

on:
  workflow_dispatch:
  workflow_call:

jobs:
  setup:
    runs-on: WIN-BUILD
    steps:
      - name: Checkout ngixi-builds repo
        uses: actions/checkout@v4
        with:
          clean: false

      - uses: ./.github/actions/setup-build
        with:
          build-dir: wasmtime-build

  build-windows:
    runs-on: WIN-BUILD
    needs: setup
    defaults:
      run:
        working-directory: wasmtime-build

    steps:

      - name: Stub Wasmtime build
        shell: pwsh
        run: |
          Write-Host "Wasmtime build stub - TODO: implement actual build"
          New-Item -ItemType Directory -Path wasmtime-assets -Force
          # Create placeholder to ensure artifact uploads
          "STUB: Wasmtime assets not yet implemented" | Out-File -Encoding utf8 wasmtime-assets/README.md
          # TODO: Add actual Wasmtime build steps here

      - name: Upload Wasmtime artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasmtime-windows-assets
          path: wasmtime-build/wasmtime-assets/