name: Build Dawn

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: WIN-BUILD
    
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    steps:
      - name: Checkout Dawn
        run: |
          if (-not (Test-Path dawn)) {
            git clone https://dawn.googlesource.com/dawn
          }
          cd dawn

      - name: Fetch dependencies
        run: |
          cd dawn
          cp scripts/standalone.gclient .gclient
          gclient sync

      - name: Configure with CMake (MSVC + install)
        run: |
            cd dawn
            cmake -S . -B out/Release -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_C_COMPILER=cl ^
            -DCMAKE_CXX_COMPILER=cl ^
            -DCMAKE_CXX_FLAGS="/DNOMINMAX" ^
            -DDAWN_ENABLE_INSTALL=ON
            
      - name: Build with CMake
        run: |
          cd dawn
          cmake --build out/Release --parallel

      - name: Install Dawn artifacts
        run: |
          cd dawn
          cmake --install out/Release --prefix install/Release
