name: Build Dawn

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: WIN-BUILD
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    steps:
      - name: Checkout Dawn
        run: |
          if (-not (Test-Path dawn)) {
            git clone https://dawn.googlesource.com/dawn
          }
          cd dawn

      - name: Fetch dependencies
        run: |
          cd dawn
          cp scripts/standalone.gclient .gclient
          gclient sync

      - name: Configure (MSVC + Ninja + install)
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
          cd dawn
          if exist out\Release rd /s /q out\Release
          cmake -S . -B out\Release -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_C_COMPILER=cl ^
            -DCMAKE_CXX_COMPILER=cl ^
            -DCMAKE_CXX_FLAGS="/DNOMINMAX /DWIN32_LEAN_AND_MEAN" ^
            -DCMAKE_SYSTEM_VERSION=10.0.26100.0 ^
            -DDAWN_ENABLE_INSTALL=ON ^
            -DBUILD_SHARED_LIBS=ON

      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
          cd dawn
          cmake --build out\Release --parallel

      - name: Install
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
          cd dawn
          cmake --install out\Release --prefix install\Release
