name: Build Dawn Ubuntu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Dawn - Linux x64
    permissions:
      contents: write
    uses: ./.github/workflows/buildDawnLinuxRelease.yml
