name: Build Wasmtime Windows

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-windows:
    runs-on: WIN-BUILD
    defaults:
      run:
        working-directory: wasmtime-build

    steps:
      - name: Checkout ngixi-builds repo
        uses: actions/checkout@v4

      - name: Set up Wasmtime build directory
        shell: pwsh
        run: |
          if (-not (Test-Path wasmtime-build)) {
            New-Item -ItemType Directory -Path wasmtime-build
          }

      - name: Stub Wasmtime build
        shell: pwsh
        run: |
          Write-Host "Wasmtime build stub - TODO: implement actual build"
          # Create placeholder to ensure artifact uploads
          "STUB: Wasmtime assets not yet implemented" | Out-File -Encoding utf8 wasmtime-assets/README.md
          # TODO: Add actual Wasmtime build steps here

      - name: Upload Wasmtime artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasmtime-windows-assets
          path: wasmtime-build/wasmtime-assets/