name: Build Wasmtime - win_x86_64-msvc

on:
  workflow_dispatch:
  workflow_call:

jobs:
  setup:
    runs-on: WIN-BUILD
    steps:
      - name: Checkout ngixi-builds repo
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-build
        with:
          build-dir: wasmtime-build

  build-windows:
    runs-on: WIN-BUILD
    needs: setup
    defaults:
      run:
        working-directory: wasmtime-build

    steps:
      - name: Checkout Wasmtime
        shell: pwsh
        run: |
          git clone ${{ vars.WASMTIME_REPO }} wasmtime

      - name: Checkout tag
        shell: pwsh
        run: |
          cd wasmtime
          git fetch --tags --force --quiet
          git checkout --quiet ${{ vars.WASMTIME_TAG }}
          git rev-parse --short HEAD | Out-File -Encoding ascii ..\WASMTIME_GIT.txt

      - name: Initialize git submodules
        shell: pwsh
        run: |
          cd wasmtime
          git submodule update --init

      - name: Build Wasmtime CLI (release)
        shell: pwsh
        run: |
          cd wasmtime
          cargo build --release --target-dir target-cli

      - name: Build Wasmtime C API (release)
        shell: pwsh
        run: |
          cd wasmtime
          cargo build --release -p wasmtime-c-api --target-dir target-capi

      - name: Create CLI tar archive
        shell: pwsh
        run: |
          cd wasmtime/target-cli/release
          tar -czf wasmtime_cli_win_x86_64.tar.gz wasmtime.exe
          Move-Item -Force wasmtime_cli_win_x86_64.tar.gz ../../..

      - name: Create C API tar archive
        shell: pwsh
        run: |
          cd wasmtime/target-capi/release
          tar -czf wasmtime_capi_win_x86_64.tar.gz *.dll *.lib
          Move-Item -Force wasmtime_capi_win_x86_64.tar.gz ../../..

      - name: Upload Wasmtime artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasmtime-windows-assets
          path: |
            wasmtime-build/wasmtime_cli_win_x86_64.tar.gz
            wasmtime-build/wasmtime_capi_win_x86_64.tar.gz
            wasmtime-build/WASMTIME_GIT.txt
