name: Build Dawn Ubuntu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Dawn - Linux x64
    runs-on: LIN-BUILD
    permissions:
      contents: write

    container:
      image: ubuntu:22.04
      options: --user root --init --rm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Dawn Linux
        uses: ./.github/actions/build-dawn-linux

      - name: FORCE KILL CONTAINER
        if: always()
        shell: bash
        run: |
          echo "FORCE KILLING CONTAINER - NO MERCY"
          # Kill ALL processes except init
          kill -9 -1 2>/dev/null || true
          # Kill everything that might be running
          pkill -9 -f ".*" 2>/dev/null || true
          # Exit immediately
          exit 0
