name: Build Dawn Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Dawn - Windows x64
    runs-on: WIN-BUILD
    permissions:
      contents: write
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0
    defaults:
      run:
        working-directory: dawn-nightly

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Dawn Windows
        uses: ./.github/actions/build-dawn-windows
