name: Build Dawn Windows & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: WIN-BUILD
    permissions:
      contents: write
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    steps:
      - name: Checkout ngixi-builds repo
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Load build versions
        shell: pwsh
        run: |
          Get-Content .github/workflows/build-versions.env | ForEach-Object {
            if ($_ -match '^([^=]+)=(.*)$') {
              $key = $matches[1].ToUpper()
              $value = $matches[2]
              Write-Host "Setting $key=$value"
              "$key=$value" | Out-File -Encoding utf8 -Append $env:GITHUB_ENV
            }
          }

      - name: Checkout Dawn
        run: |
          if (-not (Test-Path dawn)) {
            git clone $env:DAWN_REPO dawn
          }

      - name: Checkout tag
        shell: pwsh
        run: |
          cd dawn
          git fetch --tags --force --quiet
          git checkout --quiet "$env:DAWN_TAG"
          git rev-parse --short HEAD | Out-File -Encoding ascii ..\DAWN_GIT.txt

      - name: Fetch deps
        run: |
          cd dawn
          cp scripts/standalone.gclient .gclient
          gclient sync

      # Monolithic DLL => one webgpu_dawn.dll
      - name: Configure (monolithic SHARED)
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
          cd dawn
          cmake -S . -B out\mono-shared -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_C_COMPILER=cl ^
            -DCMAKE_CXX_COMPILER=cl ^
            -DCMAKE_CXX_FLAGS="/DNOMINMAX /DWIN32_LEAN_AND_MEAN" ^
            -DCMAKE_SYSTEM_VERSION=10.0.26100.0 ^
            -DBUILD_SHARED_LIBS=OFF ^
            -DDAWN_BUILD_MONOLITHIC_LIBRARY=SHARED ^
            -DDAWN_ENABLE_INSTALL=ON

      - name: Build (monolithic SHARED)
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
          cd dawn
          cmake --build out\mono-shared --parallel

      - name: Install (monolithic SHARED)
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
          cd dawn
          cmake --install out\mono-shared --prefix install\mono-shared

      # Monolithic static => one webgpu_dawn.lib
      - name: Configure (monolithic STATIC)
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
          cd dawn
          cmake -S . -B out\mono-static -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_C_COMPILER=cl ^
            -DCMAKE_CXX_COMPILER=cl ^
            -DCMAKE_CXX_FLAGS="/DNOMINMAX /DWIN32_LEAN_AND_MEAN" ^
            -DCMAKE_SYSTEM_VERSION=10.0.26100.0 ^
            -DBUILD_SHARED_LIBS=OFF ^
            -DDAWN_BUILD_MONOLITHIC_LIBRARY=STATIC ^
            -DDAWN_ENABLE_INSTALL=ON

      - name: Build (monolithic STATIC)
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
          cd dawn
          cmake --build out\mono-static --parallel

      - name: Install (monolithic STATIC)
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
          cd dawn
          cmake --install out\mono-static --prefix install\mono-static

      - name: Zip installs
        shell: pwsh
        run: |
          cd dawn
          Compress-Archive -Path .\install\mono-shared -DestinationPath "..\dawn-windows-x64-mono-shared-$env:DAWN_TAG.zip" -Force
          Compress-Archive -Path .\install\mono-static -DestinationPath "..\dawn-windows-x64-mono-static-$env:DAWN_TAG.zip" -Force
          Get-FileHash "..\dawn-windows-x64-mono-*.zip" -Algorithm SHA256 |
            ForEach-Object { "$($_.Hash)  $($_.Path)" } | Out-File -Encoding ascii "..\SHA256SUMS"

      - name: Create Release and upload assets
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        with:
          tag_name: ngixi-assets-${{ env.NGIXI_ASSET_VERSION }}
          target_commitish: ${{ github.sha }}
          name: NGIXI Assets ${{ env.NGIXI_ASSET_VERSION }} (Dawn ${{ env.DAWN_TAG }})
          body: |
            NGIXI Assets v${{ env.NGIXI_ASSET_VERSION }}
            Built from Dawn tag `${{ env.DAWN_TAG }}`.
            Assets are raw CMake install trees for monolithic SHARED and STATIC.
            DAWN_GIT.txt contains the exact commit. SHA256SUMS included.
          files: |
            dawn-windows-x64-mono-shared-*.zip
            dawn-windows-x64-mono-static-*.zip
            SHA256SUMS
            DAWN_GIT.txt
          fail_on_unmatched_files: true
          overwrite_files: true
