name: Build Assets

on:
  workflow_dispatch:

jobs:
  build-wasmtime:
    uses: ./.github/workflows/build-wasmtime-windows.yml

  build-dawn:
    uses: ./.github/workflows/build-dawn-windows.yml
    needs: build-wasmtime

  assemble-and-release:
    runs-on: lin-build
    needs: build-dawn
    permissions:
      contents: write

    steps:
      - name: Checkout ngixi-builds repo
        uses: actions/checkout@v4
        with:
          clean: false        

      - name: Download Dawn assets
        uses: actions/download-artifact@v4
        with:
          name: dawn-windows-assets
          path: all_assets_windows/dawn

      - name: Download Wasmtime assets
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: wasmtime-windows-assets
          path: all_assets_windows/wasmtime

      - name: Copy metadata files
        shell: bash
        run: |
          cp all_assets_windows/dawn/DAWN_GIT.txt . 2>/dev/null || true
          cp all_assets_windows/dawn/DEPENDENTS.txt . 2>/dev/null || true

      - name: Zip assets
        shell: bash
        run: |
          cd all_assets_windows
          zip -r ../all_assets_windows.zip .
          cd ..
          sha256sum all_assets_windows.zip > SHA256SUMS

      - name: Create Release and upload assets
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        with:
          tag_name: ngixi-assets-${{ vars.NGIXI_ASSET_VERSION }}
          target_commitish: ${{ github.sha }}
          name: NGIXI Assets ${{ vars.NGIXI_ASSET_VERSION }} (Dawn ${{ vars.DAWN_TAG }})
          body: |
            NGIXI Assets v${{ vars.NGIXI_ASSET_VERSION }}
            Dawn: ${{ vars.DAWN_TAG }}
            Wasmtime: TODO

            Assets are a mix of various build outputs which ngixi knows how to consume (or will).
          files: |
            all_assets_windows.zip
            SHA256SUMS
            DAWN_GIT.txt
            DEPENDENTS.txt
          fail_on_unmatched_files: true