name: Build Dawn Ubuntu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Dawn - Linux x64
    runs-on: LIN-BUILD
    permissions:
      contents: write

    container:
      image: ubuntu:22.04
      options: --user root

    steps:
      - name: Build Dawn Linux
        uses: ./.github/actions/build-dawn-linux
