name: Build Zig Win32 Bindings

on:
  workflow_dispatch:
  workflow_call:

jobs:
  setup:
    runs-on: WIN-BUILD
    steps:
      - name: Checkout ngixi-builds repo
        uses: actions/checkout@v4
        with:
          clean: false

      - uses: ./.github/actions/setup-windows-build
        with:
          build-dir: zig-win32-build

  build-zig:
    runs-on: WIN-BUILD
    needs: setup
    permissions:
      contents: write
    defaults:
      run:
        working-directory: zig-win32-build

    steps:
      - name: Clone ZigWin32Gen
        shell: pwsh
        run: |
          # Remove existing directory if it exists
          if (Test-Path zigwin32gen) {
            Remove-Item zigwin32gen -Recurse -Force
          }
          git clone ${{ vars.ZIGGEN_REPO }} zigwin32gen

      - name: Checkout ZigWin32Gen tag
        shell: pwsh
        run: |
          cd zigwin32gen
          git fetch --tags --force --quiet
          git checkout --quiet ${{ vars.ZIGGEN_TAG }}
          git rev-parse --short HEAD | Out-File -Encoding ascii ..\ZIG_WIN32_GIT.txt

      - name: Build ZigWin32Gen
        shell: pwsh
        run: |
          cd zigwin32gen
          zig build

      - name: Setup Zig bindings repository
        shell: pwsh
        run: |
          $repoName = "ngixi-zig-win32"
          $repoPath = "../$repoName"

          # Create directory for the separate repo
          New-Item -ItemType Directory -Path $repoPath -Force

          # Initialize git repo
          git -C $repoPath init
          git -C $repoPath config user.name "ngixi-builds"
          git -C $repoPath config user.email "builds@ngixi.com"

          # Copy zig-out contents to the repo
          Copy-Item -Recurse "zigwin32gen/zig-out/*" $repoPath/ -Force
          Copy-Item "ZIG_WIN32_GIT.txt" $repoPath/

          # Commit and tag
          git -C $repoPath add .
          $commitMsg = "Zig Win32 Bindings v${{ vars.ZIGGEN_TAG }}"
          git -C $repoPath commit -m $commitMsg
          git -C $repoPath tag "v${{ vars.ZIGGEN_TAG }}"

      - name: Create Zig Win32 Release
        uses: softprops/action-gh-release@v2
        with:
          repository: ngixi/ngixi-zig-win32
          tag_name: v${{ vars.ZIGGEN_TAG }}
          target_commitish: v${{ vars.ZIGGEN_TAG }}
          name: Zig Win32 Bindings ${{ vars.ZIGGEN_TAG }}
          body: |
            Zig Windows API Bindings v${{ vars.ZIGGEN_TAG }}
            Generated from ${{ vars.ZIGGEN_REPO }}
          files: |
            zigwin32gen/zig-out/**
