name: Build Dawn Linux Release Template

on:
  workflow_call:

jobs:
  build-linux:
    runs-on: LIN-BUILD
    permissions:
      contents: write
    
    container:
      image: ubuntu:22.04
      options: --user root

    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y \
            git \
            curl \
            python3 \
            python3-pip \
            pkg-config \
            ninja-build \
            cmake \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            mesa-common-dev \
            libx11-xcb-dev \
            ca-certificates \
            wget

      - name: Install Go 1.23+
        run: |
          wget -q https://go.dev/dl/go1.23.0.linux-amd64.tar.gz
          tar -C /usr/local -xzf go1.23.0.linux-amd64.tar.gz
          echo "/usr/local/go/bin" >> $GITHUB_PATH

      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git /opt/depot_tools
          echo "/opt/depot_tools" >> $GITHUB_PATH

      - name: Configure Git
        run: |
          git config --global user.email "build@ngixi.local"
          git config --global user.name "NGIXI Build Bot"
          git config --global --add safe.directory '*'

      - name: Checkout Dawn
        run: |
          git clone https://dawn.googlesource.com/dawn ${{github.workspace}}/dawn
          cd ${{github.workspace}}/dawn
          cp scripts/standalone.gclient .gclient

      - name: Fetch dependencies with gclient
        run: |
          export PATH="/opt/depot_tools:/usr/local/go/bin:$PATH"
          cd ${{github.workspace}}/dawn
          gclient sync

      - name: Configure Dawn (CMake + Ninja)
        run: |
          cd ${{github.workspace}}/dawn
          mkdir -p out/Release
          cd out/Release
          cmake -GNinja \
            -DCMAKE_BUILD_TYPE=Release \
            -DDAWN_BUILD_MONOLITHIC_LIBRARY=SHARED \
            -DDAWN_ENABLE_INSTALL=ON \
            ../..

      - name: Build Dawn
        run: |
          cd ${{github.workspace}}/dawn/out/Release
          ninja

      - name: Test build artifacts
        run: |
          echo "Build completed successfully!"
          ls -lah ${{github.workspace}}/dawn/out/Release/
          echo "Listing shared libraries:"
          find ${{github.workspace}}/dawn/out/Release/ -name "*.so" -o -name "*.a" | head -20
