name: Build Dawn

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: WIN-BUILD
    
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ngixi-builds
        
      - name: Setup MSVC
        run: |
          & "${{ github.workspace }}\ngixi-builds\.github\workflows\scripts\setup-msvc.ps1"
          
      - name: Setup Windows SDK
        run: |
          & "${{ github.workspace }}\ngixi-builds\.github\workflows\scripts\setup-windows-sdk.ps1"
          
      - name: Checkout Dawn
        run: |
          if (-not (Test-Path dawn)) {
            git clone https://dawn.googlesource.com/dawn
          }
          cd dawn

      - name: Fetch dependencies
        run: |
          cd dawn
          python tools/fetch_dawn_dependencies.py

      - name: Configure CMake
        run: |
          cd dawn
          cmake -S . -B out/Release -DDAWN_FETCH_DEPENDENCIES=ON -DDAWN_ENABLE_INSTALL=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DDAWN_BUILD_MONOLITHIC_LIBRARY=OFF -GNinja

      - name: Build Dawn
        run: |
          cd dawn
          cmake --build out/Release --parallel

      - name: Install Dawn
        run: |
          cd dawn
          cmake --install out/Release --prefix install/Release
