name: Build Zig Nightly - win_x86_64-msvc

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  setup:
    runs-on: WIN-BUILD
    steps:
      - name: Checkout ngixi-builds repo
        uses: actions/checkout@v4
        with:
          clean: true

      - uses: ./.github/actions/setup-build
        with:
          build-dir: zig-nightly-build

  build-zig:
    runs-on: WIN-BUILD
    needs: setup
    permissions:
      contents: write
    defaults:
      run:
        working-directory: zig-nightly-build

    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Clone Zig repository
        shell: pwsh
        run: |
          git clone ${{ vars.ZIG_REPO }} zig

      - name: Build Zig
        shell: pwsh
        run: |
          cd zig
          zig build -Doptimize=ReleaseFast

      - name: Verify build
        shell: pwsh
        run: |
          $zigExe = "zig\zig-out\bin\zig.exe"
          if (Test-Path $zigExe) {
            Write-Host "Build successful - zig.exe exists"
            & $zigExe version
          } else {
            Write-Error "Build failed - zig.exe not found at $zigExe"
            exit 1
          }


